services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-net
    mem_limit: 1g # 1GB memory limit

  redis:
    image: redis:8.4
    command: redis-server --save 10 1 --loglevel warning  # Persist data every 10 seconds if at least one value changed
    volumes:
      - redis-data:/data  # persistent Redis storage
    networks:
      - app-net

volumes:
  redis-data:  # Named volume for Redis persistence

networks:
  app-net:
    driver: bridge